controller/endpointcontroller.php, tests/controller/EndpointControllerTest.php
@guruz the header is currently e.g.:
```
"769b302348905574f8588008f86d19ce"
```
Due to strange behaviour in [core](https://github.com/owncloud/core/blame/34f5541088e99367a8bcdc1ca2ba4fa8524eec68/lib/public/appframework/http/response.php#L220), but you can still just keep an eye on that string. it's just longer then 32chars.
Fix #2
=> Add an Etag header for the request

controller/endpointcontroller.php, js/app.js, tests/controller/EndpointControllerTest.php
This hides the :bell: when no app wants to use notifications :cry: 
@PVince81 @karlitschek as discussed
=> Stop polling when app is disabled

css/styles.css, js/app.js, js/notification.js
=> Actions should trigger jQuery event on the body

appinfo/app.php, tests/Unit/AppInfo/AppTest.php
1. Enable `Notifications` and `Two Factor Test Provider`
2. Login
3. Do **not** solve the 2FA thing yet
Page is displayed
Page reloads all few seconds.
@ChristophWurst mind reviewing ? ;)
=> Do not enable Notifications on the login/ pages

css/styles.css
Before:
After:
@owncloud/design @pmaier1 ok ?
=> Bold subject

js/notification.js
Tested on OC9 and OC10, no difference to see compared to hard coded `<img>`. Please never use these elements ever again, since theming should be possible (and be done) thru CSS, not JS.
=> No hardcoded img to support theming

.travis.yml, appinfo/routes.php, lib/Controller/EndpointController.php, tests/Unit/Controller/EndpointControllerTest.php
requires https://github.com/owncloud/core/pull/28168
=> Move OCS calls to app framework - consumes less resources

js/notification.js
1. Setup customgroups app
1. Create custom group "test"
1. Create a user "user1"
1. Add user "user1" to custom group "test"
1. Login as "user1"
1. Check notification
Before this fix: the title was escaped and appeared with `&quot;`
After this fix: no escaping, proper display
Since we're using jquery's `text` here it will already render as plain text and no escaping is needed.
=> Don't escape link text title

appinfo/app.php
This is required to correctly match the logic URL when use with SAML - to avoid a redirect loop caused by including the notifications app on the login page.
=> Correctly match the login url

.travis.yml
This is the ``stable10`` branch of ``notifications``. It is only valid to test it against ``stable10`` in ``core``. Testing against ``core`` ``master`` is no longer going to work because that has moved on.
=> [stable10] Only test against core stable10

tests/acceptance/features/bootstrap/bootstrap.php
Remove the trailing slash just to make it the same format as elsewhere.
It might avoid some confusion in future, by having the format of all these ``addPSR4`` calls the same.
It works with or without the trailing ``/``
=> Standardize addPSR4 target folder format

Makefile
Template folder wasn't being included in the package, which leads to a crash. Package is correctly generated with this fix.
=> Include the template folder in the Makefile

appinfo/app.php, lib/AppInfo/Application.php
Force the notification event setup to be called explicitly in the app.php file
Fix https://github.com/owncloud/notifications/issues/169
=> Fix app loading

lib/Command/Generate.php
For https://github.com/owncloud/client/pull/6240
Do you agree with @dragotin 's idea from the client PR to put the link text into the link property too?
```
notifications:generate [-u|--user USER] [-g|--group GROUP] [--] <subject> [<message>] [<link>] [<linktext>]
```
=> occ: Provide arguments for link and linktext

lib/Mailer/NotificationMailer.php
1. Setup OC 10.0.8 code
2. Setup system cron
3. Make sure the update notification background job triggers and sends a notification (you might need to either change the update server to put a newer version or fake the version or your installation)
4. Let the cron.php job run or run it manually from the ownCloud server
Exception is thrown and email isn't sent
```
{"reqId":"ctSPDH6FkuJxMXzspkDw","level":3,"time":"2018-05-29T08:05:06+00:00","remoteAddr":"","user":"--","app":"notifications","method":"--","url":"--","message":"Exception: {\"Exception\":\"OCP\\\\Session\\\\Exceptions\\\\SessionNotAvailableException\",\"Message\":\"Session has been closed - no further changes to the session are allowed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Session\\\/Memory.ph …
```
=> Fix notification not being sent by email if system cron is set

lib/Mailer/NotificationMailer.php, lib/Mailer/NotificationMailerAdapter.php, templates/mail/htmlmail.php, templates/mail/plaintextmail.php, tests/Unit/Mailer/NotificationMailerAdapterTest.php, tests/Unit/Mailer/NotificationMailerTest.php, tests/acceptance/features/apiNotifications/email-notifications.feature
Email's title will contain the url of the server sending the notification, and the email's body will contain the notification's link. Previously, the notification's link was present in both title and body.
Partial fix of https://github.com/owncloud/notifications/issues/186 (more changes might be needed for a better message)
=> Adjust email message

appinfo/Migrations/Version20180604132522.php
Target scenario should be fixed with this.
There are other scenarios not tested at the moment such as migrations from 9.0.x and 9.1.x but I don't expect problems with them (forcing the datatype shouldn't cause issues).
Note that the fix won't affect installations that have been already migrated. Those installations are expected to be manually fixed already.
=> Fix migration from 8.2.11 to 10.0.x with postgresql

templates/mail/htmlmail.php, templates/mail/plaintextmail.php, tests/acceptance/features/apiNotifications/email-notifications.feature
Backport of https://github.com/owncloud/notifications/pull/210 to stable10
Partial fix for https://github.com/owncloud/core/issues/31876
=> [stable10] Include the product name in the mail for the notifications

.drone.yml
This makes the ``branches`` list the same in both ``stable10`` and ``master`` - which avoids dumb conflicts when this line is modified.
=> Add stable10 to branches list to match with yml in stable10

.drone.yml
1) remove the ``su-exec www-data``
2) test both API and webUI acceptance test scenarios against the Apache server in drone.
(previously the API acceptance tests were using their "default" PHP dev server on localhost, which gets fired up if no TEST_SERVER_URL is set.)
=> su-exec www-data is not needed for acceptance tests

tests/Unit/AppInfo/ApplicationTest.php
Should fix https://github.com/owncloud/update-testing/issues/10
Because we can't expect the event to work if we didn't register it.
The fact that it worked so far was just pure luck...
=> Register Symfony listener for testing events

appinfo/info.xml
1) notifications app is installed, enabled and used by some core acceptance test suites
2) when developers bump the core master version because their PR has a DB migration, then they need notifications app max-version to cope with that
For now, we can put max-version ``11.0.0`` here, while there is no release happening.
Currently when we need to release the app, then we are backing out max-version to 10.* anyway. So we will not actually release notifications app just yet with max-version ``11.0.0``
When we sort out the semver changes, then we can adjust again.
=> Allow max-version 11.0.0.* so CI runs for developers

Makefile, phpcs.xml, tests/acceptance/features/bootstrap/NotificationsContext.php, vendor-bin/php_codesniffer/composer.json
Like was merged in core in https://github.com/owncloud/core/pull/34191
So that we know if we break our own rules for acceptance test code style.
=> Add php codesniffer

.drone.yml, appinfo/info.xml, composer.json, composer.lock, vendor-bin/behat/composer.json
core stable10 no longer supports PHP 5.6
https://github.com/owncloud/core/pull/34698
=> Drop PHP 5.6

tests/acceptance/features/apiNotifications/email-notifications.feature
there was a fix for
`Given these users have been created: # FeatureContext::theseUsersHaveBeenCreated()`
so when is there is no email address in the table no email address will be set https://github.com/owncloud/core/pull/34810
the notification test did not set it, so it failed
=> create the user with default attributes (including email addr)

composer.lock, lib/AppInfo/Application.php, lib/Controller/EndpointController.php, lib/Mailer/NotificationMailer.php, lib/Mailer/NotificationMailerAdapter.php, phpunit.xml, tests/Unit/AppInfo/AppTest.php, tests/Unit/AppInfo/ApplicationTest.php, tests/Unit/AppTest.php, tests/Unit/Command/GenerateTest.php, tests/Unit/Controller/EndpointControllerTest.php, tests/Unit/HandlerTest.php, tests/Unit/Mailer/NotificationMailerTest.php, tests/acceptance/features/bootstrap/NotificationsContext.php
1) Adjust PHPUnit Framework namespace for PHPUnit6 
2) phpunit enable failOnRisky failOnWarning 
3) remove unused use statements 
4) Updating bamarni/composer-bin-plugin (v1.2.0 => v1.3.0)
=> Phpunit 5 6

lib/Handler.php
Backport #130 
This was missing from `stable10` branch of notifications app.
=> [stable10] Fixes #129 - only set icon in case an icon is available

tests/acceptance/features/apiNotifications/delete-notifications.feature, tests/acceptance/features/apiNotifications/email-notifications.feature, tests/acceptance/features/apiNotifications/notifications-content.feature, tests/acceptance/features/apiNotifications/statuscodes.feature, tests/acceptance/features/cliNotifications/sendNotifications.feature
that changed in core https://github.com/owncloud/core/pull/35438
=> Adjust create user steps

tests/acceptance/features/apiNotifications/statuscodes.feature, tests/acceptance/features/bootstrap/NotificationsContext.php
The test-step did never send the username in the post-request, so it would only work with the user "test1", because that is what the testing app uses as default to create the notification
=> correct test step to send also the username when creating notification

templates/mail/htmlmail.php, templates/mail/plaintextmail.php
`Hello` was hard coded in the mail templates.
Fixes https://github.com/owncloud/enterprise/issues/4067
=> Add `Hello` as translatable string to the mail templates

lib/Handler.php
`doctrine/dbal` was updated yesterday in core https://github.com/owncloud/core/pull/38647
Some methods have been deprecated, and `phan` reports those and fails the CI.
Suppress the deprecation warnings for now.
I raised issue #336 to actually adjust the code "some time".
=> Suppress PhanDeprecatedFunction for doctrine/dbal changes

lib/Mailer/NotificationMailer.php
Displays the configured sender name and no longer just the email address.
Behaviour has been adapted to the [Activity App](https://github.com/owncloud/activity/blob/12a7ffe4566e6a5a55a95570f62306c2819edef5/lib/MailQueueHandler.php#L195-L208).
=> Fix: Mail sender name

lib/AppInfo/Application.php, lib/Controller/EndpointController.php, tests/Unit/Controller/EndpointControllerTest.php
Transform relative URLs to absolute URLs for API endpoints to ensure compatibility with other clients.
Fixes: 
- https://github.com/owncloud/core/issues/38888
=> Provide get/list api link resource as absolute url

tests/acceptance/features/bootstrap/NotificationsContext.php
See errors in nightly like: https://drone.owncloud.com/owncloud/notifications/1693/14/10
```
Scenario: Create notifications                                             # /var/www/owncloud/testrunner/apps/notifications/tests/acceptance/features/webUINotifications/displayNotificationsOnWebUI.feature:16
When user "Alice" is sent a notification with                            # NotificationsContext::userIsSentANotificationWith()
| app         | notificationsacceptancetesting |
| timestamp   | 144958517                      |
| subject     | Acceptance Testing             |
| link        | https://owncloud.org/blog      |
| message     | Notifications in ownCloud      |
| object_type | blog                           |
| object_id   | 9483                           |
Warning: strpos() expects …
```
=> [tests-only] Send the correct string to substituteInLineCodes

tests/acceptance/features/bootstrap/NotificationsContext.php, tests/acceptance/features/bootstrap/bootstrap.php
Related https://github.com/owncloud/QA/issues/694
- add strict type checking on acceptace test code
**note** this PR was generated by a automated script
=> [Tests-Only] enforce strict type checking in acceptace tests code

.drone.star
In CI we still run acceptance tests with oracle database
In other apps and oc10 core we only run unit tests with oracle database. 
so to make it consistent remove acceptance tests with oracle database in CI.
=> [CI] dont run acceptance tests with oracle database

.drone.star, tests/acceptance/features/apiNotifications/email-notifications.feature
https://github.com/owncloud/core/pull/40442 changed the email server used in tests from mailhog to inbucket. It also changed the tag used in feature files from `@mailhog` to `@email`
So make the same change here.
Issue https://github.com/owncloud/QA/issues/771
=> [tests-only] [full-ci] Change mailhog test tag to email

phpstan.neon
```
php -d zend.enable_gc=0 vendor-bin/phpstan/vendor/bin/phpstan analyse --memory-limit=4G --configuration=./phpstan.neon --no-progress --level=5 appinfo lib
⚠️  You're using a deprecated config option excludes_analyse. ⚠️️
Parameter excludes_analyse has been deprecated so use excludePaths only from now on.
[OK] No errors                                                                                    
```
Adjust `phpstan.neon` to use the new `excludePaths` to avoid this warning.
- Part of issue: https://github.com/owncloud/QA/issues/745
> Note: This PR was made by an automated script, in case something is not right I'll take care of it manually.
=> Replace excludes_analyse with excludePaths in phpstan.neon

lib/Command/Generate.php, lib/Command/RepairNotifications.php
Symfony 5 will require this, so be prepared.
For Symfony 4 it is optional.
Preparation for https://github.com/owncloud/core/issues/39630
=> Always return an int from Symfony Command execute method

appinfo/Migrations/Version20170801152524.php, appinfo/Migrations/Version20180119080933.php
In preparation of php8.2 support - see https://php.watch/versions/8.2/$%7Bvar%7D-string-interpolation-deprecated
Similar to core https://github.com/owncloud/core/pull/40995
=> fix: drop usage of ${}
