owncloud/notifications

- .travis.yml
This reverts commit 96ea412ae6e8d7cda00087cf72dfec31cf95aece.
> Revert "Test against the notification-manager branch for now"

- css/styles.css
- js/app.js
- js/notification.js
@nickvergessen 
Fix #4 
Fix #5 
Fix #6
> Make action buttons work

- css/styles.css
Smaller height when only one notification or none, better emptycontent style, size on mobile
Please review @nickvergessen @PVince81 @Henni @owncloud/designers
> more style fixes

- controller/endpointcontroller.php
- tests/controller/EndpointControllerTest.php
> Correctly deal with notifications of disabled apps

- appinfo/info.xml
> Set the default_enabled flag

- appinfo/app.php
- tests/appinfo/AppTest.php
Fix owncloud/core#19406
@davitol @PVince81
> Only add the JS and CSS when not on public pages

- appinfo/app.php
- tests/appinfo/AppTest.php
This covers the comments from https://github.com/owncloud/notifications/pull/29#issuecomment-143785298
as I just realised that the login page otherwise queries for notifications :see_no_evil: 
@PVince81
> Also check if the user is logged in

- lib/handler.php
> Fix doc blocks of the methods

- README.md
- appinfo/info.xml
- js/app.js
Really just super-low-priority :)
> Minor text typos

- controller/endpointcontroller.php
- js/app.js
- tests/controller/EndpointControllerTest.php
Fix owncloud/core#19502
@davitol
> Use a different status code for "No notifiers"

- css/styles.css
Fixes https://github.com/owncloud/notifications/issues/16
@nickvergessen
> Fix button styles

- appinfo/application.php
- appinfo/routes.php
Wrong file header and unused imports because the files were copied from other projects
> Clean the file headers

- appinfo/info.xml
> Update the version for 9.0

- css/styles.css
@MorrisJobke @PVince81 mind testing?
Just comment out this line, so the notification app doesn't hide itself:
https://github.com/owncloud/notifications/blob/d672d5331b8fe354520d4e083daed2ea20130382/controller/endpointcontroller.php#L74-74
> Fix the emptycontent in the dropdown

- appinfo/application.php
- appinfo/database.xml
- appinfo/info.xml
- appinfo/routes.php
- controller/endpointcontroller.php
- js/app.js
- js/notification.js
- lib/capabilities.php
- lib/handler.php
- tests/appinfo/RoutesTest.php
- tests/controller/EndpointControllerTest.php
- tests/lib/CapabilitiesTest.php
- tests/lib/HandlerTest.php
> Issue 43 ocs api

- controller/endpointcontroller.php
- lib/handler.php
- tests/unit/controller/EndpointControllerTest.php
- tests/unit/lib/HandlerTest.php
> Use a date time object instead of a timestamp

- docs/notification-workflow.md
- docs/ocs-endpoint-v1.md
> Add documentation to the repository

- tests/unit/appinfo/AppTest.php
- tests/unit/appinfo/ApplicationTest.php
- tests/unit/appinfo/RoutesTest.php
- tests/unit/lib/HandlerTest.php
> Add unit test group for DB depending tests

- appinfo/info.xml
> App is not related to filesysystem

- controller/endpointcontroller.php
- lib/app.php
- lib/handler.php
- tests/integration/app/appinfo/app.php
- tests/integration/app/controller.php
- tests/integration/app/notifier.php
- tests/unit/appinfo/AppTest.php
- tests/unit/controller/EndpointControllerTest.php
- tests/unit/lib/AppTest.php
- tests/unit/lib/HandlerTest.php
> OCP\Notification api is now public

- js/app.js
> Trigger browser web notification api when polling has a new notification

- appinfo/info.xml
Otherwise that won't work, it are unique keys :)
> Merge fields

- css/styles.css
- js/app.js
Fix #60 
The error from #60 happens, when you perform an action on a notification which does not succeed. The counter between notifications and the available notifications in the UI are then off, so you can have notifications, although the counter is 0 which shows the empty content message additionally to the content.
Other commits are styling fixes.
@PVince81 @tomneedham
> Issue 60 no content and content

- js/notification.js
> Limit messages to 100 chars soft and 120 chars hard

- js/notification.js
> [9.0] Limit messages to 100 chars soft and 120 chars hard

- js/app.js
> Better error message when polling failed

- appinfo/info.xml
> added website, bugs, repository

- js/app.js
- js/notification.js
Fixes https://github.com/owncloud/notifications/issues/106
Prevent "&quot" to appear neither in the title not message.
Fixes https://github.com/owncloud/notifications/issues/107
Fix action button event handler.
> Fix actions and escaping

- js/app.js
- js/notification.js
Backport https://github.com/owncloud/notifications/pull/108 to stable10
> Stable10 fix actions

- js/notification.js
Backport of https://github.com/owncloud/notifications/pull/110 to stable10
> [stable10] Don't escape link text title

- css/styles.css
> Make sure buttons stay in place even if the messages are really long

- css/styles.css
Backport of https://github.com/owncloud/notifications/pull/115 to stable10
> [stable10] Make sure buttons stay in place even if the messages are really long

- appinfo/app.php
Backport of https://github.com/owncloud/notifications/pull/120 to stable10
> [stable10] Backport of login page protection for shibboleth users with active shib sessions

- CHANGELOG.md
- appinfo/info.xml
@patrickjahns @SergioBertolinSG FYI
This will be bundled in 10.0.4 RC2 and contains a shib fix.
> Bump version + changelog for 10.0.4

- lib/Handler.php
> only set icon in case an icon is available

- .travis.yml
- appinfo/Migrations/Version20180119080933.php
- lib/Handler.php
- tests/.travis/before_install.sh
- tests/.travis/before_install_oracle_module.sh
- tests/.travis/core_install.sh
- tests/.travis/custom.ini
- tests/Unit/HandlerTest.php
> [stable10] Merge pull request #133 from owncloud/add-oracle

- lib/Command/Generate.php
- tests/Unit/Command/GenerateTest.php
Otherwise `occ notifications:generate --group xx` is broken 🤦‍♂️
> Fix group notification create and write command test

- lib/Command/Generate.php
- tests/Unit/Command/GenerateTest.php
backport of https://github.com/owncloud/notifications/pull/144 to stable10
> [stable10] Fix group notification create and write command test

- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiNotifications/delete-notifications.feature
- tests/acceptance/features/apiNotifications/notifications-content.feature
- tests/acceptance/features/apiNotifications/statuscodes.feature
- tests/acceptance/features/bootstrap/NotificationsContext.php
- tests/acceptance/features/bootstrap/WebUINotificationsContext.php
- tests/acceptance/features/bootstrap/bootstrap.php
- tests/acceptance/features/lib/NotificationsAppDialog.php
- tests/acceptance/features/lib/NotificationsEnabledOwncloudPage.php
- tests/acceptance/features/webUINotifications/displayNotificationsOnWebUI.feature
- tests/acceptance/run.sh
1. refactored the acceptance tests to be able to run UI and API test steps from one feature file
2. UI tests infrastructure
3. first simple UI test
> enhance acceptance tests to be UI-test ready

- appinfo/app.php
- appinfo/info.xml
- appinfo/routes.php
- js/personal_settings.js
- lib/App.php
- lib/AppInfo/Application.php
- lib/Configuration/OptionsStorage.php
- lib/Controller/NotificationOptionsController.php
- lib/Mailer/NotificationMailer.php
- lib/Mailer/NotificationMailerAdapter.php
- lib/Panels/Personal/NotificationsPanel.php
- templates/panels/personal/notifications.php
- tests/Unit/AppInfo/AppTest.php
- tests/Unit/AppInfo/ApplicationTest.php
- tests/Unit/AppTest.php
- tests/Unit/Configuration/OptionsStorageTest.php
- tests/Unit/Controller/NotificationOptionsControllerTest.php
- tests/Unit/Mailer/NotificationMailerAdapterTest.php
- tests/Unit/Mailer/NotificationMailerTest.php
- tests/Unit/Panels/Personal/NotificationsPanelTest.php
Add new feature to send notifications via email
> Email notifications

- appinfo/app.php
- appinfo/info.xml
- appinfo/routes.php
- js/personal_settings.js
- lib/App.php
- lib/AppInfo/Application.php
- lib/Configuration/OptionsStorage.php
- lib/Controller/NotificationOptionsController.php
- lib/Mailer/NotificationMailer.php
- lib/Mailer/NotificationMailerAdapter.php
- lib/Panels/Personal/NotificationsPanel.php
- templates/panels/personal/notifications.php
- tests/Unit/AppInfo/AppTest.php
- tests/Unit/AppInfo/ApplicationTest.php
- tests/Unit/AppTest.php
- tests/Unit/Configuration/OptionsStorageTest.php
- tests/Unit/Controller/NotificationOptionsControllerTest.php
- tests/Unit/Mailer/NotificationMailerAdapterTest.php
- tests/Unit/Mailer/NotificationMailerTest.php
- tests/Unit/Panels/Personal/NotificationsPanelTest.php
Backport of https://github.com/owncloud/notifications/pull/147 to stable10
It will require ownCloud 10.0.8
> [stable10] Email notifications

- tests/acceptance/config/behat.yml
- tests/acceptance/features/bootstrap/NotificationsContext.php
- tests/acceptance/run.sh
to match core changes in https://github.com/owncloud/core/pull/30943
> Remove /ocs/ from end of acceptance tests baseUrl

- lib/Mailer/NotificationMailer.php
- templates/mail/htmlmail.php
- templates/mail/plaintextmail.php
Backport of https://github.com/owncloud/notifications/pull/157 to stable10
> [stable10] Email templates

- lib/Mailer/NotificationMailer.php
- templates/mail/htmlmail.php
- templates/mail/plaintextmail.php
Use templates to generate the email message
> Use email templates to generate the mail messages

- Makefile
Backport of https://github.com/owncloud/notifications/pull/167 to stable10
> [stable10] Include the template folder in the Makefile

- lib/Controller/EndpointController.php
> [stable10] Allow CORS requests to list notifications

- lib/Mailer/NotificationMailerAdapter.php
- tests/Unit/Mailer/NotificationMailerAdapterTest.php
Improve log messages for better debugging
> Change log messages for better debugging

- .drone.yml
enables scrutinizer uploads by drone CI
> scrutinizer upload

- lib/Command/Generate.php
For https://github.com/owncloud/client/pull/6240
front port of #172
> occ: Provide argument for link

- CHANGELOG.md
> Update changelog for 0.3.3 / 10.0.8

- .drone.yml
- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiNotifications/email-notifications.feature
- tests/acceptance/features/bootstrap/NotificationsContext.php
- tests/acceptance/run.sh
solves https://github.com/owncloud/QA/issues/537
depends on https://github.com/owncloud/core/pull/31079
> acceptance tests for email notifications

- tests/acceptance/features/bootstrap/NotificationsContext.php
> improve error reporting in acceptance tests

- lib/Mailer/NotificationMailer.php
- lib/Mailer/NotificationMailerAdapter.php
- templates/mail/htmlmail.php
- templates/mail/plaintextmail.php
- tests/Unit/Mailer/NotificationMailerAdapterTest.php
- tests/Unit/Mailer/NotificationMailerTest.php
Backport of https://github.com/owncloud/notifications/pull/187 to stable10
> [stable10] Adjust email message

- appinfo/Migrations/Version20180604132522.php
Backport of https://github.com/owncloud/notifications/pull/194 to stable10
> [stable10] Fix migration from 8.2.11 to 10.0.x with postgresql

- .drone.yml
Main motivation was to have build failure information in #builds channel
Second Motivation was to cleanup some of the steps with recent learnings for defaults
Note: once approved/merged - needs a backport for this app
> Cleanup drone yml

- .drone.yml
> [stable10] Cleanup drone yml

- CHANGELOG.md
- appinfo/info.xml
master for version increase only: https://github.com/owncloud/notifications/pull/203
> [stable10] Increase version to 0.3.4 + changelog

- appinfo/info.xml
- templates/mail/htmlmail.php
- templates/mail/plaintextmail.php
> Add common footer to notifications

- appinfo/info.xml
- templates/mail/htmlmail.php
- templates/mail/plaintextmail.php
> [Stable10] Add common footer to notifications

- templates/mail/htmlmail.php
- templates/mail/plaintextmail.php
Include a "Hello" line in the templates. Partially fixes https://github.com/owncloud/core/issues/31876
> Add "hello" in the mail templates

- templates/mail/htmlmail.php
- templates/mail/plaintextmail.php
- tests/acceptance/features/apiNotifications/email-notifications.feature
Partial fix for https://github.com/owncloud/core/issues/31876#issuecomment-400329984
> Include the product name in the mail for the notifications

- tests/acceptance/features/apiNotifications/delete-notifications.feature
- tests/acceptance/features/apiNotifications/email-notifications.feature
- tests/acceptance/features/apiNotifications/notifications-content.feature
- tests/acceptance/features/apiNotifications/statuscodes.feature
- tests/acceptance/features/bootstrap/NotificationsContext.php
- tests/acceptance/features/webUINotifications/displayNotificationsOnWebUI.feature
Core acceptance test steps were refactored by https://github.com/owncloud/core/pull/32121
Make the needed changes here in this app.
> Fixup refactored core gherkin steps

- tests/acceptance/features/bootstrap/NotificationsContext.php
> [stable10] Remove resetAppConfigs - it is not needed here

- tests/acceptance/features/bootstrap/NotificationsContext.php
- tests/acceptance/features/lib/Notification.php
- tests/acceptance/features/webUINotifications/displayNotificationsOnWebUI.feature
> [stable10] UI test to check correctness of the link

- .drone.yml
Backport of https://github.com/owncloud/notifications/pull/231#issuecomment-417605928
> add PHP7.2 to stable10

- l10n/.tx/config
- l10n/cs_CZ.js
- l10n/cs_CZ.json
- l10n/de.js
- l10n/de.json
- l10n/de_DE.js
- l10n/de_DE.json
- l10n/es.js
- l10n/es.json
- l10n/eu.js
- l10n/eu.json
- l10n/fr.js
- l10n/fr.json
- l10n/id.js
- l10n/id.json
- l10n/pt_BR.js
- l10n/pt_BR.json
- l10n/ru.js
- l10n/ru.json
- l10n/sq.js
- l10n/sq.json
- l10n/th_TH.js
- l10n/th_TH.json
There were no translations before, so this is just a copy of the translations from master.
> [stable10] Backport translations from master, initial version

- .drone.yml
> [stable10] su-exec www-data is not needed for acceptance tests

- CHANGELOG.md
- tests/Unit/AppInfo/ApplicationTest.php
Backport of https://github.com/owncloud/notifications/pull/237 to stable10
> [stable10] Register Symfony listener for testing events

- tests/acceptance/features/apiNotifications/email-notifications.feature
- tests/acceptance/features/webUINotifications/displayNotificationsOnWebUI.feature
1) indent feature files by 2 characters
2)  remove hard-coded user1 password, display name and email
> Test refactor 20181004

- tests/acceptance/features/apiNotifications/delete-notifications.feature
- tests/acceptance/features/apiNotifications/notifications-content.feature
- tests/acceptance/features/apiNotifications/statuscodes.feature
> Adjust user creation test steps

- .drone.yml
- .gitignore
Remove some old and no-longer-relevant things in ``.gitignore``
And a little bit of format-standardizing in the notify section of drone.
> Remove unneeded lines from gitignore

- .drone.yml
- tests/acceptance/config/behat.yml
- tests/acceptance/features/bootstrap/NotificationsContext.php
- tests/acceptance/features/cliNotifications/sendNotifications.feature
Add cli tests through occ command.
#242
:robot:
> add cli tests for notifications

- .drone.yml
- appinfo/info.xml
- composer.json
- composer.lock
- tests/acceptance/features/bootstrap/NotificationsContext.php
- tests/acceptance/features/bootstrap/bootstrap.php
- vendor-bin/behat/composer.json
> [stable10] drop php 5.6

- Makefile
- composer.lock
- lib/AppInfo/Application.php
- lib/Controller/EndpointController.php
- lib/Mailer/NotificationMailer.php
- lib/Mailer/NotificationMailerAdapter.php
- phpunit.xml
- tests/Unit/AppInfo/AppTest.php
- tests/Unit/AppInfo/ApplicationTest.php
- tests/Unit/AppTest.php
- tests/Unit/Command/GenerateTest.php
- tests/Unit/Controller/EndpointControllerTest.php
- tests/Unit/HandlerTest.php
- tests/Unit/Mailer/NotificationMailerTest.php
- tests/acceptance/features/apiNotifications/email-notifications.feature
- tests/acceptance/features/bootstrap/NotificationsContext.php
Backport PRs:
#268 create the user with default attributes (including email addr)
#269 PHPUnit6
#272 Fix makefile for tar format and excluded files
> [stable10] Backport waiting PRs as at 2019-04-03

- tests/acceptance/features/cliNotifications/sendNotifications.feature
- tests/acceptance/features/webUINotifications/displayNotificationsOnWebUI.feature
> Adjust create user test steps

- .drone.yml
Add drone matrices to run test against latest stable release tarball.
Related Issue https://github.com/owncloud/QA/issues/611
> Run tests against latest stable release tarball

- .drone.starlark
- .drone.yml
- composer.json
- composer.lock
- phpunit.xml
- tests/Unit/AppInfo/AppTest.php
- tests/Unit/AppInfo/ApplicationTest.php
- tests/Unit/AppTest.php
- tests/Unit/Command/GenerateTest.php
- tests/Unit/Configuration/OptionsStorageTest.php
- tests/Unit/Controller/EndpointControllerTest.php
- tests/Unit/Controller/NotificationOptionsControllerTest.php
- tests/Unit/HandlerTest.php
- tests/Unit/Mailer/NotificationMailerAdapterTest.php
- tests/Unit/Mailer/NotificationMailerTest.php
- tests/Unit/Panels/Personal/NotificationsPanelTest.php
- vendor-bin/behat/composer.json
Similar to https://github.com/owncloud/configreport/pull/121
> Adjust tests

- .drone.starlark
- tests/Unit/Command/GenerateTest.php
- tests/Unit/Mailer/NotificationMailerTest.php
- vendor-bin/owncloud-codestyle/composer.json
like done in core https://github.com/owncloud/core/pull/36580
and apply latest drone starlark code changes
Note: there was no effect here on `.drone.yml`
> Coding standard 2.0.0

- tests/acceptance/features/apiNotifications/notifications-content.feature
- tests/acceptance/features/cliNotifications/sendNotifications.feature
Fixes #300 
Fix failing tests after the change in core by owncloud/core#36651
Add headings to the tables in feature files.
Note: This needs additional changes on core to pass. This will pass on 2020-01-02 (at earliest)
> Fix failing tests due to change in core steps: add table headings

- tests/acceptance/features/bootstrap/NotificationsContext.php
- vendor-bin/behat/composer.json
Needed because of owncloud/core#36999
> [Tests-Only] Update guzzle for testing to 6.5

- .drone.star
- lib/App.php
- lib/Command/Generate.php
- lib/Controller/EndpointController.php
- lib/Handler.php
- lib/Mailer/NotificationMailer.php
- phpstan.neon
- vendor-bin/phpstan/composer.json
Related - owncloud/QA#642
Update phpstan to 0.12
> [Tests-Only] Update phpstan to latest version

- .drone.star
- .phan/config.php
- lib/Handler.php
- vendor-bin/phan/composer.json
Part of https://github.com/owncloud/QA/issues/643
> [Tests-Only] Bump phan 2.7 & Run phan in CI

- tests/Unit/Controller/NotificationOptionsControllerTest.php
- tests/Unit/Mailer/NotificationMailerTest.php
- tests/Unit/Panels/Personal/NotificationsPanelTest.php
- vendor-bin/behat/composer.json
Part of https://github.com/owncloud/QA/issues/647
> Implement phpunit v8

- lib/Command/Generate.php
> Fix lib/Command/Generate execute() to return 0

- tests/acceptance/features/apiNotifications/delete-notifications.feature
- tests/acceptance/features/apiNotifications/email-notifications.feature
- tests/acceptance/features/apiNotifications/notifications-content.feature
- tests/acceptance/features/apiNotifications/statuscodes.feature
- tests/acceptance/features/cliNotifications/sendNotifications.feature
- tests/acceptance/features/webUINotifications/displayNotificationsOnWebUI.feature
Similar to what was done in core recently.
> Use realistic usernames

- tests/acceptance/features/webUINotifications/displayAdminNotificationsOnWebUI.feature
- tests/acceptance/features/webUINotifications/displayNotificationsOnWebUI.feature
Fix failing acceptance tests due to changes in `core`
- Fixes https://github.com/owncloud/notifications/issues/317
> [Tests-only] Fix failing tests after core changes

- CHANGELOG.md
- appinfo/info.xml
Due to https://github.com/owncloud/notifications/issues/321#issuecomment-658352856
> Merge back release 0.5.1 to start over 

- CHANGELOG.md
- appinfo/info.xml
- sonar-project.properties
> Merge back Release 0.5.3

- CHANGELOG.md
- appinfo/info.xml
- sonar-project.properties
> Merge back Release 0.5.4

- tests/acceptance/features/bootstrap/NotificationsContext.php
core PR https://github.com/owncloud/core/pull/39036 changed the parameters of various test helper functions. Adjust the calls.
> [tests-only] [full-ci] Adjust calls to test helper functions

- tests/acceptance/features/apiNotifications/delete-notifications.feature
- tests/acceptance/features/apiNotifications/email-notifications.feature
- tests/acceptance/features/apiNotifications/notifications-content.feature
- tests/acceptance/features/apiNotifications/statuscodes.feature
- tests/acceptance/features/cliNotifications/sendNotifications.feature
- tests/acceptance/features/webUINotifications/displayAdminNotificationsOnWebUI.feature
- tests/acceptance/features/webUINotifications/displayNotificationsOnWebUI.feature
Interspacing between two scenarios is made consistent as documented https://github.com/owncloud/docs-server/pull/697/files#diff-12a0f404a5bbbda65e50018a487cd725797106d670f4308b921d2081dc4b3516R1129-R1154:~:text=more%20relevant%20discussion.-,%3D%3D%3D%3D%20Inter%2Dscenario%20spacings,%2D%2D%2D%2D,-Commenting%20on%20lines
- Part of https://github.com/owncloud/QA/issues/769
- :robot:
> [full-ci] [tests-only] Refactored inter scenarios space

- .drone.star
- appinfo/Migrations/Version20180119080933.php
- composer.json
- composer.lock
- lib/Capabilities.php
- lib/Command/Generate.php
- lib/Command/RepairNotifications.php
- lib/Notifier.php
- templates/panels/personal/notifications.php
- tests/acceptance/features/bootstrap/NotificationsContext.php
- tests/unit/Command/GenerateTest.php
- tests/unit/Command/RepairNotificationsTest.php
- vendor-bin/behat/composer.json
- vendor-bin/owncloud-codestyle/composer.json
- vendor-bin/php_codesniffer/composer.json
- vendor-bin/phpstan/composer.json
- update `.drone.star` with current CI code from activity app
- update tool dependencies
- update coding-standard to v4 and apply to the code
> [full-ci] CI tool changes

- vendor-bin/behat/composer.json
> [tests-only] [full-ci] Bump to Symfony5 in acceptance tests

- .drone.star
- remove the use of `drone_token`
- adjust the use of the `cache_s3` tokens to use the names now available
Part of issue https://github.com/owncloud/QA/issues/818
> [CI][full-ci]Update drone file of notifications
